import 'babel-polyfill';
import './Slashr';
// import { Slashr } from './Slashr';
export * from './Slashr';
export * from './Form';
export * from './Grid';
export * from './Router';
export * from './MenuSlider';
export * from './Slider';
export * from './api';
export * from './App';
export * from './Dialog';
export * from './Element';
export * from './Menu';
export * from './Calendar';
export * from './Document';
export * from './BodyPortal';
export * from './TextEditor';
export * from './Icon';
export * from './IconButton';
export * from './Button';
export * from './Footer';
export * from './ProgressIndicator';
// export default Slashr;
//export * from './Ui';
export {observable,action,computed} from "mobx";